### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by SathishRaju** [OfficeDev/office-addin-validator#20] opened 2017-12-02 01:04 UTC
Error running the addin validator in mac sierra Os.

env: node\r: No such file or directory

**Comment by ClaytonBrawley** [comment] 2017-12-14 15:48
I am also having this issue.

**Comment by jaredfolkins** [comment] 2017-12-15 22:02
## Root cause

DOS line endings are not compatible with Unix based systems. 

http://www.cs.toronto.edu/~krueger/csc209h/tut/line-endings.html

## Fix

On OSX, find where validate-office-addin is installed.

```$``` ```which validate-office-addin```

Open the file with VI.

```$``` ```vi /usr/local/bin/validate-office-addin```

Fix the line endings of the file.

```:set ff=unix```

Write/Quit

```:wq```

Run the command again and it will work.

**Comment by lindalu-MSFT** [comment] 2019-08-01 00:02
Closing all issues since this repo is being archived and no longer maintained.

**Closed by lindalu-MSFT** 2019-08-01 00:02 UTC
